### ISSUE TITLE
Object of type <ModelName> is not JSON serializable

### ISSUE THREAD

**Issue by manuel-held** [ptav/django-inlineedit#24]
Hi, ive got a 500 Internal Server Error when i change a ForeignKey. Message is:

Object of type <ModelName> is not JSON serializable

in the ajax Request.

But changes are saved to the Database. 

Django 3.1 
Python 3.8.5

**Comment by manuel-held** [comment]
No one else with this Problem?

**Comment by ptav** [comment]
Hi snookie, I just fixed a problem in display_value that fix your issue. Let us know if that works
